'use strict';
const fs=require('fs'), vm=require('vm'), assert=require('assert');
const ctx={};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('apps-script/ecoflot_server_guards.gs','utf8'),ctx);
const headers=['Request ID','\u0421\u0441\u044b\u043b\u043a\u0430','\u0422\u0435\u043b\u0435\u0444\u043e\u043d'];
const sheet=rows=>({getLastRow:()=>rows.length+1,getRange:()=>({getDisplayValues:()=>rows})});
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
test('shared Profi URL does not merge independent orders',()=>assert.equal(ctx.ecoflotFindDuplicateV3_(sheet([['old','https://profi.ru/rabota/remont/tasks/','70000000000']]),headers,{requestId:'new',link:'https://profi.ru/rabota/remont/tasks/',phone:'70000000000'}),null));
test('same request ID remains duplicate',()=>assert.equal(ctx.ecoflotFindDuplicateV3_(sheet([['old','https://profi.ru/rabota/remont/tasks/','']]),headers,{requestId:'old',link:''}).reason,'request_id'));
test('same phone is not an order ID',()=>assert.equal(ctx.ecoflotFindDuplicateV3_(sheet([['old','https://example.com/order/11111','70000000000']]),headers,{requestId:'new',link:'https://example.com/order/22222',phone:'70000000000'}),null));
test('same specific order URL is duplicate',()=>assert.equal(ctx.ecoflotFindDuplicateV3_(sheet([['old','https://example.com/order/12345','']]),headers,{requestId:'new',link:'https://example.com/order/12345?utm_source=test'}).reason,'specific_link'));
test('different query IDs not merged',()=>assert.notEqual(ctx.ecoflotSpecificUrlV3_('https://example.com/detail.php?id=12345'),ctx.ecoflotSpecificUrlV3_('https://example.com/detail.php?id=12346')));
test('query order normalizes',()=>assert.equal(ctx.ecoflotSpecificUrlV3_('https://example.com/detail.php?type=a&id=12345'),ctx.ecoflotSpecificUrlV3_('https://example.com/detail.php?id=12345&type=a')));
test('category remains non-specific',()=>assert.equal(ctx.ecoflotSpecificUrlV3_('https://gentender.ru/search?q=1234567890123456789'),''));
test('missing schema stops write',()=>assert.throws(()=>ctx.ecoflotFindDuplicateV3_(sheet([]),[],{requestId:'x'}),/SCHEMA/));
test('missing identity stops write',()=>assert.throws(()=>ctx.ecoflotFindDuplicateV3_(sheet([]),headers,{}),/REQUIRED/));
test('lead_one requires exact single-recipient key',()=>assert.equal(ctx.ecoflotQueueItemV3_('lead_one','abc|11','{"callbackKey":"abc","chatId":"11"}').chatId,'11'));
test('unknown queue kind cannot become SENT',()=>assert.throws(()=>ctx.ecoflotQueueItemV3_('unknown','x','{}'),/UNSUPPORTED/));
test('malformed JSON cannot become SENT',()=>assert.throws(()=>ctx.ecoflotQueueItemV3_('lead_one','x','{'),/JSON/));
test('combined recipient IDs rejected',()=>assert.throws(()=>ctx.ecoflotQueueItemV3_('lead_one','abc|11,22','{"callbackKey":"abc","chatId":"11,22"}'),/RECIPIENT/));
test('key mismatch rejected',()=>assert.throws(()=>ctx.ecoflotQueueItemV3_('lead_one','abc|22','{"callbackKey":"abc","chatId":"11"}'),/MISMATCH/));
test('actual message acknowledged',()=>assert.equal(ctx.ecoflotReceiptV3_({ok:true,result:{message_id:8,chat:{id:11}}},'11').messageId,'8'));
test('count is not receipt',()=>assert.throws(()=>ctx.ecoflotReceiptV3_({ok:true,telegramSent:3},'11'),/NOT_CONFIRMED/));
test('wrong recipient not delivered',()=>assert.throws(()=>ctx.ecoflotReceiptV3_({ok:true,result:{message_id:8,chat:{id:22}}},'11'),/NOT_CONFIRMED/));
test('partial duplicate routes not complete',()=>assert.equal(ctx.ecoflotDuplicateAckV3_('x',{requestId:'x',telegramRoute:[{chatId:'11',messageId:'8'}]},'request_id',['11','22']).telegramSent,false));
test('all duplicate recipients verified',()=>assert.equal(ctx.ecoflotDuplicateAckV3_('x',{requestId:'x',telegramRoute:[{chatId:'11',messageId:'8'},{chatId:'22',messageId:'9'}]},'request_id',['11','22']).telegramSent,true));
test('no recipients cannot mean delivered',()=>assert.equal(ctx.ecoflotDuplicateAckV3_('x',{requestId:'x'},'request_id',[]).telegramSent,false));
console.log('TOTAL '+passed+' tests passed');
